client_config_backend: file
client_config_file: pydrive/client_secrets.json

client_config:
    client_id: 953199992415-et29jffs2kkgk96obqg8823254ft0jfi.apps.googleusercontent.com
    client_secret: mX2RtjOOUBIYlgBGese3V_Ag 

save_credentials: True
save_credentials_backend: file
save_credentials_file: pydrive/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
